<p><b>[TRACE]</b>&nbsp;Arguments: [ 'Test Data >>> Username: myuser123, Password: secret_sauce, Error: Epic sadface: Username and password do not match any user in this service' | 'Invalid user but valid password' ]</p><p><b>[INFO]</b>&nbsp;07-21-2025 10:14:56 AM - INFO - root : Test Data >>> Username: myuser123, Password: secret_sauce, Error: Epic sadface: Username and password do not match any user in this service</p><p><b>[TRACE]</b>&nbsp;Return: None</p>